# Generated by Django 5.1.7 on 2025-03-24 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClaimsApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimsApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rep_approval', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('dispute', 'Dispute'), ('cancelled', 'Cancelled'), ('paid', 'Paid')], default='pending', max_length=10)),
                ('dean_approval', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('dispute', 'Dispute'), ('cancelled', 'Cancelled'), ('paid', 'Paid')], default='pending', max_length=10)),
                ('acc_approval', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('dispute', 'Dispute'), ('cancelled', 'Cancelled'), ('paid', 'Paid')], default='pending', max_length=10)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClaimsApp.claims')),
            ],
        ),
    ]
