# Generated by Django 5.1.7 on 2025-04-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClaimsApp', '0002_claimsapproval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claims',
            name='end_time',
            field=models.TimeField(null=True),
        ),
    ]
