# Generated by Django 5.1.7 on 2025-04-26 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClaimsApp', '0003_alter_claims_end_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_letter', models.FileField(upload_to='uploads')),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_lec', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointing_auth', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClaimsCancel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancel_reason', models.TextField()),
                ('date_cancelled', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClaimsApp.claims')),
            ],
        ),
        migrations.CreateModel(
            name='ClaimsDispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispute_reason', models.TextField()),
                ('date_disputed', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('dispute', 'Dispute'), ('cancelled', 'Cancelled'), ('paid', 'Paid')], default='pending', max_length=10)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClaimsApp.claims')),
                ('dispute_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispute_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExamInvigilation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('dispute', 'Dispute'), ('cancelled', 'Cancelled'), ('paid', 'Paid')], default='pending', max_length=10)),
                ('start_time', models.TimeField(auto_now_add=True)),
                ('end_time', models.TimeField(null=True)),
                ('date_invigilated', models.DateField(auto_now_add=True)),
                ('date_paid', models.DateTimeField(auto_now_add=True)),
                ('amount_paid', models.PositiveIntegerField(default=0)),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SetExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('dispute', 'Dispute'), ('cancelled', 'Cancelled'), ('paid', 'Paid')], default='pending', max_length=10)),
                ('date_set', models.DateField(auto_now_add=True)),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
