# Generated by Django 5.1.7 on 2025-04-26 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClaimsApp', '0004_appointment_claimscancel_claimsdispute_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examinvigilation',
            name='exam_venue',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='examinvigilation',
            name='no_students',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='setexam',
            name='exam_paper',
            field=models.FileField(null=True, upload_to='uploads'),
        ),
    ]
