# Generated by Django 5.1.7 on 2025-04-26 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClaimsApp', '0005_examinvigilation_exam_venue_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.PositiveIntegerField()),
                ('date_paid', models.DateTimeField(auto_now_add=True)),
                ('exam_paid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClaimsApp.setexam')),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paid_to', to=settings.AUTH_USER_MODEL)),
                ('paid_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paid_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
